name: my-rssparser
version: '1.0.0'
config-version: 2
profile: my-rssparser

analysis-paths: ["analyses"]
model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

## Target
target-path: target
clean-targets: [target, dbt_packages, dbt_modules, dbt_internal_packages, logs]

vars:
  dev:
    debug_mode: true
    row_limit: 1000
  prod:
    debug_mode: false

on-run-start:
  - "{{ snowflake_create_database_schema() }}"
  - "{{ snowflake_create_file_format() }}"
  - "{{ snowflake_create_tables() }}"
#  - "{{read_sql_file('scripts/ddl/table/calendrier.sql')}}"

seeds:
    +schema: bronze 
    +delimiter: ','
    +quote_columns: false     # Don't quote column names - keeps SQL cleaner

## Models
models:
  my-rssparser:

    staging:
      +materialized: view
      +schema: raw_data
    marts:
      +materialized: table
      +schema: curated
  